# Generated by Django 5.0.1 on 2025-10-15 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyAnalytics',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger'), ('whatsapp', 'WhatsApp'), ('all', 'All Platforms')], max_length=20)),
                ('date', models.DateField()),
                ('total_messages', models.IntegerField(default=0)),
                ('incoming_messages', models.IntegerField(default=0)),
                ('outgoing_messages', models.IntegerField(default=0)),
                ('total_conversations', models.IntegerField(default=0)),
                ('new_conversations', models.IntegerField(default=0)),
                ('avg_response_time_minutes', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analytics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Daily Analytics',
                'verbose_name_plural': 'Daily Analytics',
                'db_table': 'daily_analytics',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['user', '-date'], name='daily_analy_user_id_b9eb4c_idx'), models.Index(fields=['user', 'platform', '-date'], name='daily_analy_user_id_dd4f59_idx')],
                'unique_together': {('user', 'platform', 'date')},
            },
        ),
    ]
