# Generated by Django 5.0.1 on 2025-10-15 00:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlatformAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('platform_user_id', models.CharField(help_text='User ID from the platform', max_length=255)),
                ('platform_username', models.CharField(blank=True, max_length=255, null=True)),
                ('access_token', models.TextField(help_text='Encrypted access token')),
                ('refresh_token', models.TextField(blank=True, help_text='Encrypted refresh token', null=True)),
                ('token_expires_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('last_sync_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional platform-specific data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platform_accounts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Platform Account',
                'verbose_name_plural': 'Platform Accounts',
                'db_table': 'platform_accounts',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'platform', 'platform_user_id')},
            },
        ),
    ]
