# Generated by Django 5.0.1 on 2025-10-15 00:41

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('platforms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_conversation_id', models.CharField(help_text='Conversation ID from platform', max_length=255)),
                ('participant_id', models.CharField(max_length=255)),
                ('participant_name', models.CharField(max_length=255)),
                ('participant_avatar', models.URLField(blank=True, null=True)),
                ('last_message_at', models.DateTimeField()),
                ('unread_count', models.IntegerField(default=0)),
                ('is_archived', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='platforms.platformaccount')),
            ],
            options={
                'verbose_name': 'Conversation',
                'verbose_name_plural': 'Conversations',
                'db_table': 'conversations',
                'ordering': ['-last_message_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform_message_id', models.CharField(help_text='Message ID from platform', max_length=255, unique=True)),
                ('message_type', models.CharField(choices=[('text', 'Text'), ('image', 'Image'), ('video', 'Video'), ('audio', 'Audio'), ('file', 'File'), ('sticker', 'Sticker'), ('location', 'Location')], default='text', max_length=20)),
                ('content', models.TextField(blank=True, null=True)),
                ('media_url', models.URLField(blank=True, null=True)),
                ('sender_id', models.CharField(max_length=255)),
                ('sender_name', models.CharField(max_length=255)),
                ('is_incoming', models.BooleanField(default=True, help_text='True if from user, False if sent by page/business')),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField()),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional message data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='chat_messages.conversation')),
                ('platform_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='platforms.platformaccount')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
                'db_table': 'messages',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['-last_message_at'], name='conversatio_last_me_99c95c_idx'),
        ),
        migrations.AddIndex(
            model_name='conversation',
            index=models.Index(fields=['platform_account', 'is_archived'], name='conversatio_platfor_e2eea9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('platform_account', 'platform_conversation_id')},
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['-sent_at'], name='messages_sent_at_cea072_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['conversation', '-sent_at'], name='messages_convers_1401f8_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['platform_account', 'is_read'], name='messages_platfor_a1bede_idx'),
        ),
        migrations.AddIndex(
            model_name='message',
            index=models.Index(fields=['platform_message_id'], name='messages_platfor_5413dc_idx'),
        ),
    ]
