# Generated by Django 5.0.1 on 2025-10-15 00:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebhookLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('instagram', 'Instagram'), ('messenger', 'Messenger'), ('whatsapp', 'WhatsApp')], max_length=20)),
                ('event_type', models.CharField(help_text='Type of webhook event', max_length=100)),
                ('payload', models.JSONField(help_text='Full webhook payload')),
                ('headers', models.JSONField(blank=True, default=dict, help_text='Request headers')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Webhook Log',
                'verbose_name_plural': 'Webhook Logs',
                'db_table': 'webhook_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['-created_at'], name='webhook_log_created_5dbdab_idx'), models.Index(fields=['platform', 'status'], name='webhook_log_platfor_7ab3dd_idx'), models.Index(fields=['status', '-created_at'], name='webhook_log_status_4b788b_idx')],
            },
        ),
    ]
